### ISSUE TITLE
Could not find install.sh file

### ISSUE THREAD

**Issue by guxi798** [SeanPCollins/RandomForest#1]
The `Install_Guide.pdf` step 4 stated to run `install.sh` file to start the program. However, `install.sh` is not in this repository. Please instruct where to find it.
<img width="686" alt="Screenshot 2024-06-24 at 9 26 06 PM" src="https://github.com/SeanPCollins/RandomForest/assets/6333749/4d4e849e-3a76-4d7b-868f-a2cfa33311b3">

**Comment by SeanPCollins** [comment]
Added an install.sh file in the latest commit. You should now be able to run it to set up the appropriate files/structure.

**Comment by guxi798** [comment]
Could you please also share the data files `target_csv` and `descriptor_csvs`? Thanks!
